export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";

export const ADD_USERNAME = "ADD_USERNAME";
export const REMOVE_USERNAME = "REMOVE_USERNAME";


export const ADD_USERDETAILS = "ADD_USERDETAILS";
export const REMOVE_USERDETAILS= "REMOVE_USERDETAILS";

export const ADD_RELEASE_RADAR_DETAILS = "ADD_RELEASE_RADAR_DETAILS";
export const REMOVE_RELEASE_RADAR_DETAILS= "REMOVE_RELEASE_RADAR_DETAILS";